/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RolePlant;

/**
 *
 * @author hrushithaputtala
 */
public class MainPlantArea extends javax.swing.JPanel {

    /**
     * Creates new form MainPlantArea
     */
    public MainPlantArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPlantAreaLbl = new javax.swing.JLabel();
        MPAGardenPlanningBtn = new javax.swing.JButton();
        MPAEnrollinglbl = new javax.swing.JButton();
        MPAdisplayBtn = new javax.swing.JButton();
        MPAquestionsBtn = new javax.swing.JButton();
        MPARentingLandBtn = new javax.swing.JButton();

        MainPlantAreaLbl.setText("Main Working Area");

        MPAGardenPlanningBtn.setText("Garden Planning");
        MPAGardenPlanningBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPAGardenPlanningBtnActionPerformed(evt);
            }
        });

        MPAEnrollinglbl.setText("Enroll Event");
        MPAEnrollinglbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPAEnrollinglblActionPerformed(evt);
            }
        });

        MPAdisplayBtn.setText("Display Renting Land");
        MPAdisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPAdisplayBtnActionPerformed(evt);
            }
        });

        MPAquestionsBtn.setText("FAQ ");
        MPAquestionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPAquestionsBtnActionPerformed(evt);
            }
        });

        MPARentingLandBtn.setText("Renting The Land");
        MPARentingLandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPARentingLandBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MPAdisplayBtn)
                    .addComponent(MPAquestionsBtn)
                    .addComponent(MPARentingLandBtn)
                    .addComponent(MPAEnrollinglbl)
                    .addComponent(MPAGardenPlanningBtn)
                    .addComponent(MainPlantAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(MainPlantAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(MPAGardenPlanningBtn)
                .addGap(18, 18, 18)
                .addComponent(MPAEnrollinglbl)
                .addGap(30, 30, 30)
                .addComponent(MPARentingLandBtn)
                .addGap(26, 26, 26)
                .addComponent(MPAquestionsBtn)
                .addGap(32, 32, 32)
                .addComponent(MPAdisplayBtn)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MPAdisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPAdisplayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPAdisplayBtnActionPerformed

    private void MPAquestionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPAquestionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPAquestionsBtnActionPerformed

    private void MPARentingLandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPARentingLandBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPARentingLandBtnActionPerformed

    private void MPAEnrollinglblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPAEnrollinglblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPAEnrollinglblActionPerformed

    private void MPAGardenPlanningBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPAGardenPlanningBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPAGardenPlanningBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MPAEnrollinglbl;
    private javax.swing.JButton MPAGardenPlanningBtn;
    private javax.swing.JButton MPARentingLandBtn;
    private javax.swing.JButton MPAdisplayBtn;
    private javax.swing.JButton MPAquestionsBtn;
    private javax.swing.JLabel MainPlantAreaLbl;
    // End of variables declaration//GEN-END:variables
}
