/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RolePlant;

/**
 *
 * @author hrushithaputtala
 */
public class SellLandEvents extends javax.swing.JPanel {

    /**
     * Creates new form SellLandEvents
     */
    public SellLandEvents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RPsellLandCosttxt = new javax.swing.JTextField();
        RPsellLandPhonetxt = new javax.swing.JTextField();
        RPsellLandBackBtn = new javax.swing.JButton();
        RPSellLandlbl = new javax.swing.JLabel();
        RPsellLandLocationLbl = new javax.swing.JLabel();
        RPsellLandAreaLbl = new javax.swing.JLabel();
        RPsellLandCostLbl = new javax.swing.JLabel();
        RPsellLandPhnLbl = new javax.swing.JLabel();
        RPsellLandDisplayBtn = new javax.swing.JButton();
        RPSellLandLocationtxt = new javax.swing.JTextField();
        RPsellLandAreatxt = new javax.swing.JTextField();

        RPsellLandBackBtn.setText("<<Back");
        RPsellLandBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPsellLandBackBtnActionPerformed(evt);
            }
        });

        RPSellLandlbl.setBackground(new java.awt.Color(204, 204, 255));
        RPSellLandlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RPSellLandlbl.setText("Sell Land");

        RPsellLandLocationLbl.setText("Location:");

        RPsellLandAreaLbl.setText("Area:");

        RPsellLandCostLbl.setText("Cost/Month:");

        RPsellLandPhnLbl.setText("Phone Number:");

        RPsellLandDisplayBtn.setText("Display  For Rent");
        RPsellLandDisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPsellLandDisplayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RPsellLandLocationLbl)
                            .addComponent(RPsellLandPhnLbl)
                            .addComponent(RPsellLandCostLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RPsellLandAreaLbl)
                            .addComponent(RPSellLandlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RPsellLandAreatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPsellLandCosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPsellLandPhonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPSellLandLocationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(RPsellLandDisplayBtn)))
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RPsellLandBackBtn)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(RPSellLandlbl)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPsellLandLocationLbl)
                    .addComponent(RPSellLandLocationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPsellLandAreaLbl)
                    .addComponent(RPsellLandAreatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPsellLandCostLbl)
                    .addComponent(RPsellLandCosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPsellLandPhnLbl)
                    .addComponent(RPsellLandPhonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RPsellLandDisplayBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(RPsellLandBackBtn)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RPsellLandBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPsellLandBackBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_RPsellLandBackBtnActionPerformed

    private void RPsellLandDisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPsellLandDisplayBtnActionPerformed
        // TODO add your handling code here:

        if (RPSellLandLocationtxt.getText().trim().isEmpty() ||
            RPsellLandAreatxt.getText().trim().isEmpty() ||
            RPsellLandCosttxt.getText().trim().isEmpty() ||
            RPsellLandPhonetxt.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,"All fields are mandatory");

        }
        else{
            String location = RPSellLandLocationtxt.getText();
            String area = RPsellLandAreatxt.getText();
            String price = RPsellLandCosttxt.getText();
            String con = RPsellLandPhonetxt.getText();
            LandSellWorkRequest req = new LandSellWorkRequest();
            req.setMessage(location);
            req.setArea(area);
            req.setPricePerMonth(price);
            req.setContact(Integer.parseInt(con));
            req.setSender(account);

            //Organization allFarmerOrganizations = null;
            boolean found = false;
            for (Network n : business.getNetworkList()) {
                for (SubNetwork sub : n.getSubNet()) {
                    if (sub.toString().equalsIgnoreCase(account.getCity())) {

                        for (Enterprise e : sub.getEnterpriseDirectory().getEnterpriseList()) {
                            for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                                if (org instanceof EndUserOrganization) {

                                    req.setStatus("Posted");
                                    org.getWorkQueue().getWorkRequestList().add(req);
                                    account.getWorkQueue().getWorkRequestList().add(req);
                                    found = true;

                                    break;
                                }

                            }
                        }
                    }
                    // else JOptionPane.showMessageDialog(null,"No farmer organizations found in your city !");
                }

            }
            if(found){
                JOptionPane.showMessageDialog(null,"Your Land is posted on forum");

            }

        }

    }//GEN-LAST:event_RPsellLandDisplayBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RPSellLandLocationtxt;
    private javax.swing.JLabel RPSellLandlbl;
    private javax.swing.JLabel RPsellLandAreaLbl;
    private javax.swing.JTextField RPsellLandAreatxt;
    private javax.swing.JButton RPsellLandBackBtn;
    private javax.swing.JLabel RPsellLandCostLbl;
    private javax.swing.JTextField RPsellLandCosttxt;
    private javax.swing.JButton RPsellLandDisplayBtn;
    private javax.swing.JLabel RPsellLandLocationLbl;
    private javax.swing.JLabel RPsellLandPhnLbl;
    private javax.swing.JTextField RPsellLandPhonetxt;
    // End of variables declaration//GEN-END:variables
}
