/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Business.DB4OUtil.DB4OUtil;
import Business.ecosystem;
import Business.ConfigureEcosystem;
import DB4OUtil.Validator;
import Enterprise.AgricultureEnterprise;
import Enterprise.Enterprise;
import Network.network;
import Network.subnetwork;
import organization.organization;
import Role.role;
import UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.planterRole.PlanterProfilePageJPanel;

/**
 *
 * @author shalinishree
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    private ecosystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public mainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        loginjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        signupjButton = new javax.swing.JButton();
        logoutjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1096, 530));
        setPreferredSize(new java.awt.Dimension(1096, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(161, 530));

        jLabel1.setText("UserName");

        jLabel2.setText("Password");

        loginjButton.setText("Login");
        loginjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("    New Here!");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        signupjButton.setText("SignUp");
        signupjButton.setBorder(null);
        signupjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupjButtonActionPerformed(evt);
            }
        });

        logoutjButton.setText("LogOut");
        logoutjButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(username)
                    .addComponent(Password)
                    .addComponent(loginjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signupjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(logoutjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(loginjButton)
                .addGap(18, 18, 18)
                .addComponent(logoutjButton)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signupjButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                                                                                                          Farming System");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), null, null, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel5, "card2");

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        // TODO add your handling code here:
        String userName = username.getText();
        // Get Password
        char[] passwordCharArray = Password.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        //Enterprise inEnterprise = new AgricultureEnterprise();
        Enterprise inEnterprise = null;
        organization inOrganization = null;
        boolean enterpriseAdmin = false;
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : system.getNetworkList()) {
                if (userAccount == null) {
                    for (subnetwork subnet : network.getSubNet()) {
                        if (userAccount == null) {
                            //inSubNetwork=subnet;
                            //Step 2-a: Check against each enterprise
                            for (Enterprise enterprise : subnet.getEnterpriseDirectory().getEnterpriseList()) {
                                userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    //inEnterprise = new AgricultureEnterprise();
                                    //System.out.println(""+enterprise.getClass());
                                    inEnterprise = enterprise;
                                    System.out.println(enterprise.getName());
                                    enterpriseAdmin = true;
                                    break;
                                }
                                if (userAccount == null && !enterpriseAdmin) {
                                    //Step3: Check against each organization inside that enterprise
                                    for (organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                        userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                        if (userAccount != null) {
                                            inEnterprise = enterprise;
                                            inOrganization = organization;

                                            break;
                                        }
                                    }
                                } else {
                                    inEnterprise = enterprise;

                                    break;
                                }

                                if (inOrganization != null) {
                                    break;
                                }
                            }
                            if (enterpriseAdmin) {
                                break;
                            }
                            if (inEnterprise!=null) {
                                break;
                            }
                        }
                    }

                }
            }
        }
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        } else {
            CardLayout layout = (CardLayout) jPanel2.getLayout();
            jPanel2.add("workArea", userAccount.getRole().createWorkArea(jPanel2, userAccount, inOrganization, inEnterprise, system));
            layout.next(jPanel2);
        }

        loginjButton.setEnabled(false);
        logoutjButton.setEnabled(true);
        username.setEnabled(false);
        Password.setEnabled(false);
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        logoutjButton.setEnabled(false);
        username.setEnabled(true);
        Password.setEnabled(true);
        loginjButton.setEnabled(true);

        username.setText("");
        Password.setText("");

        jPanel2.removeAll();
        JPanel blankJP = new JPanel();
        jPanel2.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) jPanel2.getLayout();
        crdLyt.next(jPanel2);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void signupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupjButtonActionPerformed
        // TODO add your handling code here:
        logoutjButton.setEnabled(true);
        PlanterProfilePageJPanel ppj = new PlanterProfilePageJPanel(jPanel2,system);
        jPanel2.add("PlanterProfilePage", ppj);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_signupjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginjButton;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton signupjButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
