/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Buyer;

/**
 *
 * @author Shrimoyee
 */
public class BuyerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyerWorkAreaJPanel
     */
    public BuyerWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        intbutton1 = new javax.swing.JButton();
        replybutton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crop Name", "Quantity", "Contact Details", "Sender"
            }
        ));
        jScrollPane1.setViewportView(table1);

        intbutton1.setText(" Interested");
        intbutton1.setToolTipText("");
        intbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intbutton1ActionPerformed(evt);
            }
        });

        replybutton2.setText("Reply");
        replybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replybutton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BUYER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(intbutton1)
                        .addGap(133, 133, 133)
                        .addComponent(replybutton2)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intbutton1)
                    .addComponent(replybutton2))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void intbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intbutton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = table1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
        }

        else{
            DefaultTableModel tbl1 = (DefaultTableModel) table1.getModel();

            WorkRequest wr = (WorkRequest)tbl1.getValueAt(selectedRow,0);
            wr.setReceiver(account);
            JOptionPane.showMessageDialog(null,"Thank you for showing your interest");
            wr.setStatus("Waiting for reply from  "+account);
            populateQATable();
        }
    }//GEN-LAST:event_intbutton1ActionPerformed

    private void replybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replybutton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = table1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row");
        }

        else{

            DefaultTableModel tbl2 = (DefaultTableModel) table1.getModel();
            WorkRequest wr = (WorkRequest)tbl2.getValueAt(selectedRow,0);
            if(wr.getReceiver()!=null){
                if(wr.getReceiver().toString().equalsIgnoreCase(account.toString())){

                    String answer = JOptionPane.showInputDialog("Your Reply :");
                    wr.setAnswer(answer);
                    wr.setStatus("Completed");
                    populateQATable();
                }
                else JOptionPane.showMessageDialog(null,"Someone else already shows interest first!");
            }
            else JOptionPane.showMessageDialog(null,"Please assign the dealt to you and then proceed to reply!");
        }
    }//GEN-LAST:event_replybutton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intbutton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton replybutton2;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
