/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SellerRole;

import Business.ecosystem;
import Enterprise.Enterprise;
import UserAcc.useracc;
import Work.Request;
import Work.SellerOrg;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shrimoyee
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    useracc useracc;
    SellerOrg sellerorg;
    Enterprise enterprise;
    ecosystem business;

    /**
     * Creates new form SellerWorkAreaJPanel
     */
    public SellerWorkAreaJPanel(JPanel userProcessContainer, useracc useracc, SellerOrg sellerorg, Enterprise enterprise,ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.useracc = useracc;
        this.sellerorg = sellerorg;
        this.enterprise = enterprise;
        this.business = business;
        
        //populateMyQTable();
    
    }
 /*public void populateMyQTable(){
            DefaultTableModel dtm = (DefaultTableModel)DataTable.getModel();
        dtm.setRowCount(0);
        for(Request wk : account.getWorkQueue().getWorkRequestList()){
            if (wk instanceof SellerOrg sellerOrg){
                Object[] row1 = new Object[3];
                row1[0] = sellerOrg.getProdName();
                row1[1] = sellerOrg.getProdPrice();
                row1[2] = sellerOrg.getStock();
               
        
                 dtm.addRow(row1);
                
            }
            
        
        }*/
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProductName_seller = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ProductPrice_seller = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Stock = new javax.swing.JTextField();
        Postbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Price", "Available Stock"
            }
        ));
        jScrollPane3.setViewportView(DataTable);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seller Work Area");

        jLabel2.setText("Product Name");

        ProductName_seller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductName_sellerActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Price");

        jLabel4.setText("Available Stock");

        Postbutton.setText("Post ");
        Postbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("My Requests:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ProductName_seller, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(ProductPrice_seller, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(Postbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ProductName_seller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductPrice_seller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(Postbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PostbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostbuttonActionPerformed
        // TODO add your handling code here:

        String ProductName_seller = ProductName_seller.getText();
        String ProductPrice_seller = ProductPrice_seller.getText();
        String stock = Stock.getText();

        SellerOrg req = new SellerOrg();
        req.setProductName_seller(prodName);
        req.setProductPrice_seller(prodPrice);
        req.setStock(stock);
        req.setSender(account);

        boolean found = false;
        for (Network n : business.getNetworkList()) {
            for (SubNetwork sub : n.getSubNet()) {
                if (sub.toString().equalsIgnoreCase(account.getCity())) {

                    for (Enterprise e : sub.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {

                            if (org instanceof FarmerOrganization) {
                                req.setStatus("Posted");
                                org.getWorkQueue().getWorkRequestList().add(req);
                                account.getWorkQueue().getWorkRequestList().add(req);
                                found = true;

                                break;
                            }

                        }
                    }
                }
                // else JOptionPane.showMessageDialog(null,"No farmer organizations found in your city !");
            }

        }
        if(found){
            JOptionPane.showMessageDialog(null,"Request Posted");
            populateMyQTable();

        }

    }//GEN-LAST:event_PostbuttonActionPerformed

    private void ProductName_sellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductName_sellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductName_sellerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTable;
    private javax.swing.JButton Postbutton;
    private javax.swing.JTextField ProductName_seller;
    private javax.swing.JTextField ProductPrice_seller;
    private javax.swing.JTextField Stock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
