/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.farmer;

import Business.ecosystem;
import Enterprise.Enterprise;
import organization.farmer;
import UserAcc.useracc;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shalinishree
 */
public class farmerMainboard extends javax.swing.JPanel {

    /**
     * Creates new form farmerMainboard
     */
    JPanel userProcessContainer;
    useracc account;
    farmer farmerOrganization;
    Enterprise enterprise;
    ecosystem business;
    

    public farmerMainboard(JPanel userProcessContainer, useracc account, farmer farmerOrganization, Enterprise enterprise, ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.farmerOrganization = farmerOrganization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSellCrop = new javax.swing.JButton();
        btnAnsCummQues = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuyroducts = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        btnSellCrop.setBackground(new java.awt.Color(102, 102, 0));
        btnSellCrop.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSellCrop.setText("SELL CROP");
        btnSellCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellCropActionPerformed(evt);
            }
        });

        btnAnsCummQues.setBackground(new java.awt.Color(102, 102, 0));
        btnAnsCummQues.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnAnsCummQues.setText("FAQ");
        btnAnsCummQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsCummQuesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Farmer Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));

        btnBuyroducts.setBackground(new java.awt.Color(102, 102, 0));
        btnBuyroducts.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuyroducts.setText("BUY PRODUCTS");
        btnBuyroducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyroductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSellCrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnsCummQues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuyroducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnSellCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuyroducts, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAnsCummQues, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellCropActionPerformed
        // TODO add your handling code here:
        cropsell panel = new cropsell(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("SellMyCrop", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellCropActionPerformed

    private void btnAnsCummQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsCummQuesActionPerformed
        // TODO add your handling code here:
        farmerQA panel = new farmerQA(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("FarmerWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnsCummQuesActionPerformed

    private void btnBuyroductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyroductsActionPerformed
        // TODO add your handling code here:
        productbuy panel = new productbuy(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("buyProducts", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyroductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnsCummQues;
    private javax.swing.JButton btnBuyroducts;
    private javax.swing.JButton btnSellCrop;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
